# Generated by Django 3.2.3 on 2021-05-24 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='./products/static/products/images/%Y/%m/%d/'),
        ),
    ]
