# Generated by Django 3.2.3 on 2021-05-26 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.FileField(default=None, upload_to='images'),
            preserve_default=False,
        ),
    ]
